services:
  db:
    image: 'postgres:17.2'
    container_name: postgres-rails
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: railsdb
    volumes:
      - ./db-data:/var/lib/postgresql/data/
  redis:
    image: 'redis:7.2-alpine'
    container_name: redis-rails
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
