default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  database: railsdb
  encoding: unicode
  username: postgres
  password: password
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
#  database: The name for your **development** database

test:
  <<: *default
#  database: The name for your **test** database

production:
  <<: *default
#  database: The name for your **production**
